# 报告生成节点
# 该节点故意不调用模型 | 不是每个节点都必须调用 LLM
# 有些节点负责工具调用，有些节点负责格式化，有些节点负责路由，这是 Agent 工程中很重要的设计思想


from app.states import PaperState
from app.tools.report_writer import build_report_output_path, save_markdown_report

# 在报告中体现出 retrieval evidence
def format_retrieved_evidence(retrieval_results, max_chars_per_chunk: int = 1200) -> str:
    if not retrieval_results:
        return "No retrieved evidence available."
    
    evidence_blocks = []

    for rank, retrieval_result in enumerate(retrieval_results, start=1):
        chunk = retrieval_result.chunk
        score = retrieval_result.score

        text = chunk.text.strip()
        if len(text) > max_chars_per_chunk:
            text = text[:max_chars_per_chunk] + "\n..."

        block = f"""### Rank {rank}
    - Chunk ID: {chunk.chunk_id}
    - Score: {score:.4f}
    - Char Range: {chunk.start_char} - {chunk.end_char}

    Excerpt:

    ```text
    {text}
    ```"""
        evidence_blocks.append(block)

    return "\n\n".join(evidence_blocks)


def generate_report_node(state: PaperState) -> PaperState:
    pdf_path = state.get("pdf_path", "")
    query = state.get("query", "")
    top_k = state.get("top_k", 5)
    retriever_type = state.get("retriever_type", "tfidf")
    embedding_model = state.get("embedding_model", "")

    paper_title = state.get("paper_title", "Unknown Paper")
    paper_summary = state.get("paper_summary", "")
    paper_critique = state.get("paper_critique", "")
    retrieval_results = state.get("retrieval_results", [])

    retrieved_evidence = format_retrieved_evidence(retrieval_results)

    final_report = f"""# Paper Analysis Report

## Input

- PDF: `{pdf_path}`
- Query: {query}
- Top-K: {top_k}
- Retriever Type: {retriever_type}
- Embedding Model: {embedding_model}

## Paper Title

{paper_title}

## Retrieved Evidence

{retrieved_evidence}

## Paper Summary

{paper_summary}

## Technical Critique

{paper_critique}

## Final Notes

This report was generated by a LangGraph-based RAG pipeline. The analysis is grounded in the retrieved paper chunks listed above.
"""

    output_path = build_report_output_path(pdf_path)
    save_markdown_report(final_report, output_path)

    return {
        "final_report": final_report,
        "output_path": output_path,
    }
